"""Generate ``docs/errors.md``, the table of error and warning codes, from ``tokbin.codes``.

Usage: ``python scripts/gen_errors_doc.py`` writes the file; ``--check`` exits with 1
if the file is out of date (the test suite runs this).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from tokbin import codes

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "docs" / "errors.md"

CATEGORIES = {
    "C": ("Configuration", "`ConfigError`"),
    "K": ("Contract", "`ContractError`"),
    "D": ("Data", "`DataError`, `DataQualityWarning`"),
    "F": ("Format", "`FormatError`, `SchemaVersionError`, `UnsupportedFeatureError`"),
    "I": ("Integrity", "`IntegrityError`"),
    "M": ("Compatibility", "`CompatibilityError`, `CompatibilityWarning`"),
    "R": ("Resume", "`ResumeError`"),
    "P": ("Dependencies", "`DependencyError`"),
    "S": ("Sharding", "`ShardingWarning`"),
    "X": ("Internal", "`InternalError`"),
}

HEADER = """\
# Error and warning codes

<!-- Generated by scripts/gen_errors_doc.py from src/tokbin/codes.py. Do not edit. -->

Every tokbin error and warning carries a stable code `TB-<category><number>`. A code
never changes its meaning and is never reused, even after the error is removed.

An error message has three parts: what happened, why, and what to do:

```bash
[TB-I301] Shard is missing: corpus/web/train-00003.bin
  where: tokbin.read.source.read_source
  cause: meta.json lists 13 shards for 'train'; this one is not on disk
  fix:   download the shard again and run `tokbin verify corpus/web`
```

Numbering inside a category: 1xx on-disk format, 2xx writing, 3xx reading, inspection
and verification. Some codes label warnings and facts reported in the `issues` of a
result (for example `TB-C215`, `TB-S203`) rather than exceptions.
"""


def render() -> str:
    parts = [HEADER]
    for letter, (title, classes) in CATEGORIES.items():
        entries = sorted(
            (c for c in codes.CODES.values() if c.category == letter), key=lambda c: c.id
        )
        if not entries:
            continue
        parts.append(f"\n## {letter}: {title}\n\nClasses: {classes}.\n\n")
        parts.append("| Code | Meaning |\n|---|---|\n")
        parts.extend(f"| `{c.id}` | {c.title} |\n" for c in entries)
    if codes.RETIRED:
        parts.append("\n## Retired codes\n\nNo longer issued and never reused:\n\n")
        parts.extend(f"- `{code}`\n" for code in sorted(codes.RETIRED))
    return "".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the file is outdated")
    args = parser.parse_args()
    text = render()
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.is_file() else ""
        if current != text:
            print(f"{TARGET.relative_to(ROOT)} is outdated; run python scripts/gen_errors_doc.py")
            return 1
        return 0
    TARGET.write_text(text, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
